export enum TipoPerfil {
  ADMINISTRADOR = 'ADMIN',
  SECRETARIA = 'SECRETARIA',
  CLIENTE = 'CLIENTE',
  CADASTRADOR_COMPRA = 'CAD-COMPRA',
  CADASTRADOR_FORNECEDOR = 'CAD-FORNECEDOR',
  CADASTRADOR_USUARIO = 'CAD-USUARIO',
  CADASTRADOR_VACINA = 'CAD-VACINA',
  CADASTRADOR_VACINACAO = 'CAD-VACINACAO',
}
