openapi: 3.0.3
info:
  title: API para Clínica de Imunizacação - Vacine
  description: |-

    API para clínica de imunização Vacine.

     Faz autenticação, autorização e registro de usuários. Além disso, ainda possibilita a gestão de usuários, vacinas, fornecedores, vacinacões, compras e descartes de vacinas. 

    Esta API foi criada via Swagger com base na especificação OpenAPI 3.0. 

    Instruções:
     - Para acessar as funções pelo servidor 'API Servidor' ou 'API Desenvolvimento':
       1. Acessar a API de 'Autorização'.
       2. Utilizar o endpoint '/autenticacao/jwt' informando um usuário e senha válidos.
       3. Copiar o token da resposta.
       4. Clicar na função 'Authorize'.
       5. Informar o token recebido no passo 3.    
     - Para acessar as funções pelo servidor 'API Mock':
       1. Clicar na função 'Authorize'.
       2. Informar qualquer valor no campo 'value' para o token.

       
    Links úteis:
    - [Repositório do projeto](https://github.com/georgiamcs/posPucMinas2022)

  contact:
    name: desenvolvedor
    email: georgiamcs@gmail.com
  version: 1.0.0

servers:
  - url: https://georgia2344.c42.integrator.host/mock/api
    description: API Mock
  - url: https://georgia2344.c42.integrator.host/api
    description: API Servidor
  - url: http://localhost:3005/api
    description: API Desenvolvimento
tags:
  - name: Autorização
    description: API relativa a autorização de acesso a API
  - name: Clientes
    description: API relativa a serviços para usuários do tipo clientes
  - name: Usuários
    description: API relativa a gestão de usuários
  - name: Vacinas
    description: API relativa a gestão de vacinas
  - name: Vacinações
    description: API relativa a gestão de vacinações
  - name: Descartes de vacinas
    description: API relativa a gestão de descartes de vacinas
  - name: Fornecedores de vacinas
    description: API relativa a gestão de fornecedores de vacinas
  - name: Compras de vacinas
    description: API relativa a gestão de compras de vacinas

paths:
  /autenticacao/jwt:
    post:
      tags:
        - Autorização
      summary: Efetua o login utilizando o padrão JWT (JSON Web Token)
      operationId: jwt
  /clientes/registrar:
    post:
      tags:
        - Clientes
      summary: Faz o registro de um usuário com perfil de cliente sem precisar estar logado no sistema
      operationId: registrarUsuario
  /usuarios:
    get:
      tags:
        - Usuários
      summary: Retorna a lista de todos os usuários
      operationId: gettAllUsuarios
      security:
        - api_key:
            - write:usuario
            - read:usuario
    post:
      tags:
        - Usuários
      summary: Adiciona um novo usuário
      operationId: addUsuario
      security:
        - api_key:
            - write:usuario
            - read:usuario
  /usuarios/{id}:
    get:
      tags:
        - Usuários
      summary: Consulta um usuário pelo id
      operationId: getUsuario
      security:
        - api_key:
            - write:usuarios
            - read:usuarios
    put:
      tags:
        - Usuários
      summary: Atualiza o usuário informado pelo id
      operationId: updateUsuario
      security:
        - api_key:
            - write:usuarios
            - read:usuarios
    delete:
      tags:
        - Usuários
      summary: Exclui um usuário pelo id
      operationId: deleteUsuario
      security:
        - api_key:
            - write:usuarios
            - read:usuarios
  /usuarios/trocarsenha/{id}:
    put:
      tags:
        - Usuários
      summary: Altera a senha do usuário
      operationId: trocarSenha
      security:
        - api_key:
            - write:usuarios
            - read:usuarios
  /usuarios/nome/{id}:
    get:
      tags:
        - Usuários
      summary: Consulta o nome de um usuário pelo id
      operationId: getNomeUsuario
      security:
        - api_key:
            - write:usuarios
            - read:usuarios
  /usuarios/getByTipos:
    get:
      tags:
        - Usuários
      summary: Retorna a lista de todos os usuários que são dos tipos informados apenas como nome, id e CPF
      operationId: gettAllUsuariosPorTipo
      security:
        - api_key:
            - write:usuario
            - read:usuario
  /usuarios/vacinacoes/{id}:
    get:
      tags:
        - Usuários
      summary: Retorna a lista de vacinacoes de um usuário por id
      operationId: getVacinacoesUsuario
      security:
        - api_key:
            - write:usuarios
            - read:usuarios

  /vacinas:
    get:
      tags:
        - Vacinas
      summary: Retorna a lista de todas as vacinas
      operationId: gettAllVacinas
      security:
        - api_key:
            - write:vacina
            - read:vacina
    post:
      tags:
        - Vacinas
      summary: Adiciona uma nova vacina
      operationId: addVacina
      security:
        - api_key:
            - write:vacina
            - read:vacina
  /vacinas/{id}:
    get:
      tags:
        - Vacinas
      summary: Consulta uma vacina pelo id
      operationId: getVacina
      security:
        - api_key:
            - write:vacina
            - read:vacina
    put:
      tags:
        - Vacinas
      summary: Atualiza a vacina informada pelo id
      operationId: updateVacina
      security:
        - api_key:
            - write:vacina
            - read:vacina
    delete:
      tags:
        - Vacinas
      summary: Exclui uma vacina pelo id
      operationId: deleteVacina
      security:
        - api_key:
            - write:vacina
            - read:vacina
  /vacinas/controle-estoque/{id}:
    get:
      tags:
        - Vacinas
      summary: Retorna o histórico do controle de estoque da vacina informada
      operationId: getContEstoqueVacina
      security:
        - api_key:
            - write:estoque
            - read:estoque

  /vacinacoes:
    get:
      tags:
        - Vacinações
      summary: Retorna a lista de todas as vacinações
      operationId: gettAllVacinacoes
      security:
        - api_key:
            - write:vacinacao
            - read:vacinacao
    post:
      tags:
        - Vacinações
      summary: Adiciona uma nova vacinação
      operationId: addVacinacao
      security:
        - api_key:
            - write:vacinacao
            - read:vacinacao
  /vacinacoes/{id}:
    get:
      tags:
        - Vacinações
      summary: Consulta uma vacinação pelo id
      operationId: getVacinacao
      security:
        - api_key:
            - write:vacinacoes
            - read:vacinacoes
    put:
      tags:
        - Vacinações
      summary: Atualiza a vacinação informada pelo id
      operationId: updateVacinacao
      security:
        - api_key:
            - write:vacinacao
            - read:vacinacao
    delete:
      tags:
        - Vacinações
      summary: Exclui uma vacinação pelo id
      operationId: deleteVacinacao
      security:
        - api_key:
            - write:vacinacoes
            - read:vacinacoes

  /descarte-vacinas:
    get:
      tags:
        - Descartes de vacinas
      summary: Retorna a lista de todos os descartes de vacinas
      operationId: gettAllDescartesVacinas
      security:
        - api_key:
            - write:descartes
            - read:descartes
    post:
      tags:
        - Descartes de vacinas
      summary: Adiciona um novo descarte de vacina
      operationId: addDescarteVacina
      security:
        - api_key:
            - write:descartes
            - read:descartes
  /descarte-vacinas/{id}:
    get:
      tags:
        - Descartes de vacinas
      summary: Consulta um descarte de vacina pelo id
      operationId: getDescarteVacina
      security:
        - api_key:
            - write:descartes
            - read:descartes
    put:
      tags:
        - Descartes de vacinas
      summary: Atualiza um descarte de vacina informado pelo id
      operationId: updateDescarteVacina
      security:
        - api_key:
            - write:descartes
            - read:descartes
    delete:
      tags:
        - Descartes de vacinas
      summary: Exclui um descarte de vacina pelo id
      operationId: deleteDescarteVacina
      security:
        - api_key:
            - write:descartes
            - read:descartes

  /fornecedores:
    get:
      tags:
        - Fornecedores de vacinas
      summary: Retorna a lista de todos os fornecedores
      operationId: gettAllFornecedores
      security:
        - api_key:
            - write:fornecedor
            - read:fornecedor
    post:
      tags:
        - Fornecedores de vacinas
      summary: Adiciona um novo fornecedor
      operationId: addFornecedor
      security:
        - api_key:
            - write:fornecedor
            - read:fornecedor
  /fornecedores/{id}:
    get:
      tags:
        - Fornecedores de vacinas
      summary: Consulta um fornecedor pelo id
      operationId: getFornecedor
      security:
        - api_key:
            - write:fornecedor
            - read:fornecedor
    put:
      tags:
        - Fornecedores de vacinas
      summary: Atualiza o fornecedor informado pelo id
      operationId: updateFornecedor
      security:
        - api_key:
            - write:fornecedor
            - read:fornecedor
    delete:
      tags:
        - Fornecedores de vacinas
      summary: Exclui um fornecedor pelo id
      operationId: deleteFornecedor
      security:
        - api_key:
            - write:fornecedor
            - read:fornecedor

  /compras-vacinas:
    get:
      tags:
        - Compras de vacinas
      summary: Retorna a lista de todas as compras de vacinas
      operationId: gettAllCompraVacina
      security:
        - api_key:
            - write:compras
            - read:compras
    post:
      tags:
        - Compras de vacinas
      summary: Adiciona uma nova compra de vacina
      operationId: addVacinacaoCompraVacina
      security:
        - api_key:
            - write:compras
            - read:compras
  /compras-vacinas/{id}:
    get:
      tags:
        - Compras de vacinas
      summary: Consulta uma compra de vacina pelo id
      operationId: getCompraVacina
      security:
        - api_key:
            - write:compras
            - read:compras
    put:
      tags:
        - Compras de vacinas
      summary: Atualiza a compra de vacina informada pelo id
      operationId: updateCompraVacina
      security:
        - api_key:
            - write:compras
            - read:compras
    delete:
      tags:
        - Compras de vacinas
      summary: Exclui uma compra de vacina pelo id
      operationId: deleteCompraVacina
      security:
        - api_key:
            - write:compras
            - read:compras

components:
  securitySchemes:
    api_key:
      type: http
      scheme: bearer
      bearerFormat: JWT
