openapi: 3.0.3
info:
  title: API para Clínica de Imunizacação - Vacine
  description: |-
    
    API para clínica de imunização Vacine.
    
     Faz autenticação, autorização e registro de usuários. Além disso, ainda possibilita a gestão de usuários, vacinas, fornecedores, vacinacões, compras e descartes de vacinas. 
    
    Esta API foi criada via Swagger com base na especificação OpenAPI 3.0. 

    Instruções:
     - Para acessar as funções pelo servidor 'API Servidor' ou 'API Desenvolvimento':
       1. Acessar a API de 'Autorização'.
       2. Utilizar o endpoint '/autenticacao/jwt' informando um usuário e senha válidos.
       3. Copiar o token da resposta.
       4. Clicar na função 'Authorize'.
       5. Informar o token recebido no passo 3.    
     - Para acessar as funções pelo servidor 'API Mock':
       1. Clicar na função 'Authorize'.
       2. Informar qualquer valor no campo 'value' para o token.

       
    Links úteis:
    - [Repositório do projeto](https://github.com/georgiamcs/posPucMinas2022)
    

  contact:
    name: desenvolvedor
    email: georgiamcs@gmail.com
  version: 1.0.0
servers:
  - url: https://georgia2344.c42.integrator.host/mock/api
    description: API Mock
  - url: https://georgia2344.c42.integrator.host/api
    description: API Servidor    
  - url: http://localhost:3005/api
    description: API Desenvolvimento  
tags:
  - name: Autorização
    description: API relativa a autorização de acesso a API
  - name: Usuários
    description: API relativa a gestão de usuários  
  - name: Vacinas
    description: API relativa a gestão de vacinas
  - name: Vacinações
    description: API relativa a gestão de vacinações
  - name: Descartes de vacinas
    description: API relativa a gestão de descartes de vacinas 
  - name: Fornecedores de vacinas
    description: API relativa a gestão de fornecedores de vacinas 
  - name: Compras de vacinas
    description: API relativa a gestão de compras de vacinas     
  
paths:
  /autenticacao/jwt:
    post:
      tags:
        - Autorização
      summary: Efetua o login utilizando o padrão JWT (JSON Web Token)
      operationId: jwt
  /autenticacao/registrar:
    post:
      tags:
        - Autorização
      summary: Faz o registro de um usuário com perfil de cliente
      operationId: registrarUsuario
  /usuarios:
    get:
      tags:
        - Usuários
      summary: Retorna a lista de todos os usuários
      operationId: gettAllUsuarios
      security:
        - api_key:
            - write:usuario
            - read:usuario  
    post:
      tags:
        - Usuários
      summary: Adiciona um novo usuário
      operationId: addUsuario
      security:
        - api_key:
            - write:usuario
            - read:usuario
  /usuarios/{id}:            
    get:
      tags:
        - Usuários
      summary: Consulta um usuário pelo id
      operationId: getUsuario
      security:
        - api_key:
            - write:usuarios
            - read:usuarios               
    put:
      tags:
        - Usuários
      summary: Atualiza o usuário informado pelo id
      operationId: updateUsuario
      security:
        - api_key:
            - write:usuarios
            - read:usuarios
    delete:
      tags:
        - Usuários
      summary: Exclui um usuário pelo id
      operationId: deleteUsuario
      security:
        - api_key:
            - write:usuarios
            - read:usuarios    
  
  /fornecedores:
    get:
      tags:
        - Fornecedores
      summary: Retorna a lista de todos os fornecedores
      operationId: gettAllFornecedores
      security:
        - api_key:
            - write:fornecedor
            - read:fornecedor  
    post:
      tags:
        - Fornecedores
      summary: Adiciona um novo fornecedor
      operationId: addFornecedor
      security:
        - api_key:
            - write:fornecedor
            - read:fornecedor
  /fornecedores/{id}: 
    get:
      tags:
        - Fornecedores
      summary: Consulta um fornecedor pelo id
      operationId: getFornecedor
      security:
        - api_key:
            - write:fornecedores
            - read:fornecedores     
    put:
      tags:
        - Fornecedores
      summary: Atualiza o fornecedor informado pelo id
      operationId: updateFornecedor
      security:
        - api_key:
            - write:fornecedores
            - read:fornecedores
    delete:
      tags:
        - Fornecedores
      summary: Exclui um fornecedor pelo id
      operationId: deleteFornecedor
      security:
        - api_key:
            - write:fornecedores
            - read:fornecedores   
  /fornecedores/relatorios/listagem:
    get:
      tags:
        - Fornecedores
      summary: Recupera PDF com a lista de fornecedores
      operationId: getRelatorioListagemFornecedores
      security:
        - api_key:
            - write:fornecedor
            - read:fornecedor  
  /fornecedores/exportar/listagem:
    get:
      tags:
        - Fornecedores
      summary: Recupera planilha Excel com a lista de fornecedores
      operationId: getExportarListagemFornecedores
      security:
        - api_key:
            - write:fornecedor
            - read:fornecedor  
  /produtos:
    get:
      tags:
        - Produtos
      summary: Retorna a lista de todos os produtos
      operationId: gettAllProdutos
      security:
        - api_key:
            - write:produto
            - read:produto  
    post:
      tags:
        - Produtos
      summary: Adiciona um novo produto
      operationId: addProduto
      security:
        - api_key:
            - write:produto
            - read:produto
  /produtos/{id}: 
    get:
      tags:
        - Produtos
      summary: Consulta um produto pelo id
      operationId: getProduto
      security:
        - api_key:
            - write:produtos
            - read:produtos     
    put:
      tags:
        - Produtos
      summary: Atualiza o produto informado pelo id
      operationId: updateProduto
      security:
        - api_key:
            - write:produtos
            - read:produtos
    delete:
      tags:
        - Produtos
      summary: Exclui um produto pelo id
      operationId: deleteProduto
      security:
        - api_key:
            - write:produtos
            - read:produtos   
  /produtos/{id}/listarItensCompras: 
    get:
      tags:
        - Produtos
      summary: Consulta os itens de compra que contem o produto
      operationId: getItensComprasProduto
      security:
        - api_key:
            - write:produtos
            - read:produtos                
  /produtos/{id}/indicadoresCompras: 
    get:
      tags:
        - Produtos
      summary: Consulta os indicadores de compras do produto para um determinado ano
      operationId: getindicadoresComprasProduto
      security:
        - api_key:
            - write:produtos
            - read:produtos                
  /produtos/relatorios/listagem:
    get:
      tags:
        - Produtos
      summary: Recupera PDF com a lista de produtos
      operationId: getRelatorioListagemProdutos
      security:
        - api_key:
            - write:produto
            - read:produto  
  /produtos/exportar/listagem:
    get:
      tags:
        - Produtos
      summary: Recupera planilha Excel com a lista de produtos
      operationId: getExportarListagemProdutos
      security:
        - api_key:
            - write:produto
            - read:produto              
  /vendedores:
    get:
      tags:
        - Vendedores
      summary: Retorna a lista de todos os vendedores
      operationId: gettAllVendedores
      security:
        - api_key:
            - write:vendedor
            - read:vendedor  
    post:
      tags:
        - Vendedores
      summary: Adiciona um novo vendedor
      operationId: addVendedor
      security:
        - api_key:
            - write:vendedor
            - read:vendedor
  /vendedores/{id}:            
    get:
      tags:
        - Vendedores
      summary: Consulta um vendedor pelo id
      operationId: getVendedor
      security:
        - api_key:
            - write:vendedores
            - read:vendedores   
    put:
      tags:
        - Vendedores
      summary: Atualiza o vendedor informado pelo id
      operationId: updateVendedor
      security:
        - api_key:
            - write:vendedores
            - read:vendedores
    delete:
      tags:
        - Vendedores
      summary: Exclui um vendedor pelo id
      operationId: deleteVendedor
      security:
        - api_key:
            - write:vendedores
            - read:vendedores   
  /vendedores/relatorios/listagem:
    get:
      tags:
        - Vendedores
      summary: Recupera PDF com a lista de vendedores
      operationId: getRelatorioListagemVendedores
      security:
        - api_key:
            - write:vendedor
            - read:vendedor  
  /vendedores/exportar/listagem:
    get:
      tags:
        - Vendedores
      summary: Recupera planilha Excel com a lista de vendedores
      operationId: getExportarListagemVendedores
      security:
        - api_key:
            - write:vendedor
            - read:vendedor   

  /clientes:
    get:
      tags:
        - Clientes
      summary: Retorna a lista de todos os clientes
      operationId: gettAllClientes
      security:
        - api_key:
            - write:cliente
            - read:cliente  
    post:
      tags:
        - Clientes
      summary: Adiciona um novo cliente
      operationId: addCliente
      security:
        - api_key:
            - write:cliente
            - read:cliente
  /clientes/{id}:  
    get:
      tags:
        - Clientes
      summary: Consulta um cliente pelo id
      operationId: getCliente
      security:
        - api_key:
            - write:clientes
            - read:clientes   
    put:
      tags:
        - Clientes
      summary: Atualiza o cliente informado pelo id
      operationId: updateCliente
      security:
        - api_key:
            - write:clientes
            - read:clientes
    delete:
      tags:
        - Clientes
      summary: Exclui um cliente pelo id
      operationId: deleteCliente
      security:
        - api_key:
            - write:clientes
            - read:clientes   
  /clientes/relatorios/listagem:
    get:
      tags:
        - Clientes
      summary: Recupera PDF com a lista de clientes
      operationId: getRelatorioListagemClientes
      security:
        - api_key:
            - write:cliente
            - read:cliente  
  /clientes/exportar/listagem:
    get:
      tags:
        - Clientes
      summary: Recupera planilha Excel com a lista de clientes
      operationId: getExportarListagemClientes
      security:
        - api_key:
            - write:cliente
            - read:cliente  
  /compras:
    get:
      tags:
        - Compras
      summary: Retorna a lista de todas as compras
      operationId: gettAllCompras
      security:
        - api_key:
            - write:compra
            - read:compra  
    post:
      tags:
        - Compras
      summary: Adiciona uma nova compra
      operationId: addCompra
      security:
        - api_key:
            - write:compra
            - read:compra
  /compras/{id}:  
    get:
      tags:
        - Compras
      summary: Consulta uma compra pelo id
      operationId: getCompra
      security:
        - api_key:
            - write:compras
            - read:compras   
    put:
      tags:
        - Compras
      summary: Atualiza a compra informada pelo id
      operationId: updateCompra
      security:
        - api_key:
            - write:compras
            - read:compras        
    delete:
      tags:
        - Compras
      summary: Exclui uma compra pelo id
      operationId: deleteCompra
      security:
        - api_key:
            - write:compras
            - read:compras   
  /compras/{idCompra}/itensCompra/{id}:  
    delete:
      tags:
        - Compras
      summary: Exclui um item da compra pelo id
      operationId: deleteItemCompra
      security:
        - api_key:
            - write:compras
            - read:compras            
  /compras/relatorios/listagem:
    get:
      tags:
        - Compras
      summary: Recupera PDF com a lista de compras
      operationId: getRelatorioListagemCompras
      security:
        - api_key:
            - write:compras
            - read:compras  
  /compras/exportar/listagem:
    get:
      tags:
        - Compras
      summary: Recupera planilha Excel com a lista de compras
      operationId: getExportarListagemCompras
      security:
        - api_key:
            - write:compras
            - read:compras        
  /vendas:
    get:
      tags:
        - Vendas
      summary: Retorna a lista de todas as vendas
      operationId: gettAllVendas
      security:
        - api_key:
            - write:venda
            - read:venda  
    post:
      tags:
        - Vendas
      summary: Adiciona uma nova venda
      operationId: addVenda
      security:
        - api_key:
            - write:venda
            - read:venda
  /vendas/{id}:  
    get:
      tags:
        - Vendas
      summary: Consulta uma venda pelo id
      operationId: getVenda
      security:
        - api_key:
            - write:vendas
            - read:vendas   
    put:
      tags:
        - Vendas
      summary: Atualiza a venda informada pelo id
      operationId: updateVenda
      security:
        - api_key:
            - write:vendas
            - read:vendas                 
    delete:
      tags:
        - Vendas
      summary: Exclui uma venda pelo id
      operationId: deleteVenda
      security:
        - api_key:
            - write:vendas
            - read:vendas   
  /vendas/consultas/indicadoresVendas: 
    get:
      tags:
        - Vendas
      summary: Consulta os indicadores de vendas para um determinado ano
      operationId: getindicadoresVendas
      security:
        - api_key:
            - write:vendas
            - read:vendas   
  /vendas/consultas/produtosMaisVendidos: 
    get:
      tags:
        - Vendas
      summary: Consulta os produtos mais vendidos para um determinado ano e, opcionalmente, para um cliente em particular.
      operationId: getProdutosMaisVendidos
      security:
        - api_key:
            - write:vendas
            - read:vendas               
  /vendas/relatorios/listagem:
    get:
      tags:
        - Vendas
      summary: Recupera PDF com a lista de vendas
      operationId: getRelatorioListagemVendas
      security:
        - api_key:
            - write:venda
            - read:venda  
  /vendas/exportar/listagem:
    get:
      tags:
        - Vendas
      summary: Recupera planilha Excel com a lista de vendas
      operationId: getExportarListagemVendas
      security:
        - api_key:
            - write:venda
            - read:venda              
components:
  securitySchemes:
    api_key:
      type: http
      scheme: bearer    
      bearerFormat: JWT